-- ============================================================
-- COMPANY DATABASE
-- ============================================================

CREATE DATABASE company;

USE company;


-- CREATE EMPLOYEE TABLE

CREATE TABLE employee (
    ID INT PRIMARY KEY,
    NAME VARCHAR(30),
    SALARY DECIMAL(10,2),
    DESIGNATION VARCHAR(30),
    DESTINATION VARCHAR(30),
    SUPERVISOR_ID INT
);


-- CREATE DEPARTMENT TABLE

CREATE TABLE department (
    DEPARTMENT_NO INT,
    DEPARTMENT_NAME VARCHAR(30),
    EMPLOYEE_ID INT
);


-- 1. INSERT FIVE RECORDS INTO EMPLOYEE TABLE

INSERT INTO employee
VALUES
(111,'Arun Kumar',28000,'Clerk','Mandya',NULL),
(222,'Priya Sharma',35000,'Manager','Mysore',555),
(333,'Ravi Gowda',42000,'Software Engineer','Bangalore',555),
(444,'Sneha Rao',38000,'Researcher','Hassan',222),
(555,'Kiran Shetty',55000,'Manager','Bangalore',NULL);


-- INSERT FIVE RECORDS INTO DEPARTMENT TABLE

INSERT INTO department
VALUES
(3,'Sales',111),
(4,'Research',222),
(5,'Development',333),
(5,'Development',444),
(6,'HR',555);


-- 2. DISPLAY ID, NAME AND DESIGNATION

SELECT ID, NAME, DESIGNATION FROM employee;


-- 3. RETRIEVE ALL COLUMNS IN DIFFERENT SEQUENCE

SELECT NAME, SALARY, ID, DESTINATION, DESIGNATION, SUPERVISOR_ID
FROM employee;


-- 4. DISPLAY EMPLOYEE NAME IN ALPHABETICAL ORDER

SELECT NAME FROM employee ORDER BY NAME ASC;


-- 5. SORT EMPLOYEE NAME IN DESCENDING ORDER

SELECT NAME FROM employee ORDER BY NAME DESC;


-- 6. DISPLAY NAME OF EMPLOYEES WORKING AS MANAGER

SELECT NAME FROM employee WHERE DESIGNATION = 'Manager';


-- 7. EMPLOYEE NAME NOT WORKING IN DEPARTMENT NUMBER 3

SELECT e.NAME
FROM employee e
JOIN department d ON e.ID = d.EMPLOYEE_ID
WHERE d.DEPARTMENT_NO <> 3;


-- 8. EMPLOYEE NAME AND SALARY WHERE SALARY > 30000

SELECT NAME, SALARY FROM employee WHERE SALARY > 30000;


-- 9. EMPLOYEE NAME AND DEPARTMENT NUMBER WORKING IN DEPARTMENT 4

SELECT e.NAME, d.DEPARTMENT_NO
FROM employee e
JOIN department d ON e.ID = d.EMPLOYEE_ID
WHERE d.DEPARTMENT_NO = 4;


-- 10. EMPLOYEE NAME WITH SALARY > 20000 AND DEPARTMENT 5

SELECT e.NAME
FROM employee e
JOIN department d ON e.ID = d.EMPLOYEE_ID
WHERE e.SALARY > 20000
AND d.DEPARTMENT_NO = 5;


-- 11. EMPLOYEE NAME LIVING IN MANDYA OR MYSORE

SELECT NAME
FROM employee
WHERE DESTINATION IN ('Mandya','Mysore');


-- 12. EMPLOYEE DATA NOT BELONGING TO DEPARTMENT 5 AND 6

SELECT e.*
FROM employee e
JOIN department d ON e.ID = d.EMPLOYEE_ID
WHERE d.DEPARTMENT_NO NOT IN (5,6);


-- 13. EMPLOYEE DETAILS WITH ID 111 AND 333

SELECT * FROM employee
WHERE ID IN (111,333);


-- 14. DIFFERENT DESTINATIONS AVAILABLE

SELECT DISTINCT DESTINATION FROM employee;


-- 15. COUNT NUMBER OF RECORDS IN EMPLOYEE TABLE

SELECT COUNT(*) AS TOTAL_EMPLOYEES FROM employee;


-- 16. FIND AVERAGE SALARY

SELECT AVG(SALARY) AS AVERAGE_SALARY FROM employee;


-- 17. FIND TOTAL SALARY

SELECT SUM(SALARY) AS TOTAL_SALARY FROM employee;


-- 18. FIND EMPLOYEES WORKING IN SALES DEPARTMENT

SELECT e.*
FROM employee e
JOIN department d ON e.ID = d.EMPLOYEE_ID
WHERE d.DEPARTMENT_NAME = 'Sales';


-- 19. FIND MINIMUM SALARY

SELECT MIN(SALARY) AS MINIMUM_SALARY FROM employee;


-- 20. ADD NEW ATTRIBUTE AND CHANGE BANGALORE TO HASSAN

ALTER TABLE employee ADD ADDRESS VARCHAR(30);

UPDATE employee
SET ADDRESS = 'Hassan'
WHERE DESTINATION = 'Bangalore';


-- 21. NAME OF EMPLOYEES WORKING FOR RESEARCH DEPARTMENT

SELECT e.NAME
FROM employee e
JOIN department d ON e.ID = d.EMPLOYEE_ID
WHERE d.DEPARTMENT_NAME = 'Research';


-- 22. EMPLOYEE DETAILS WITH SALARY BETWEEN 30000 AND 40000

SELECT *
FROM employee
WHERE SALARY BETWEEN 30000 AND 40000;

-- 23. No supervisor

SELECT NAME
FROM employee
WHERE SUPERVISOR_ID IS NULL;